steps:
  - name: build
    image: bitnami/laravel:12.3.1
    commands:
      # Minimal .env so Artisan works
      - echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
      - echo "APP_ENV=production" >> .env
      - echo "DB_CONNECTION=sqlite" >> .env
      - echo "DB_DATABASE=:memory:" >> .env
      # Backend
      - composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader
      # Frontend
      - npm install
      - npm run build

  # 3) Deploy over FTP to Hostinger (Laravel + React build)
  - name: deploy
    image: alpine:3.20
    environment:
      FTP_CREDS:
        from_secret: ftp_creds
      APP_ENV_CONTENTS:
        from_secret: app_env_contents
      # where to upload on Hostinger (adjust if you use subdomains)
      API_PATH: "public_html"       # Laravel project root on Hostinger (with .htaccess rewrite to /public)
    commands:
      - apk add --no-cache lftp bash zip

      # (A) Write production .env from secret (optional but recommended)
      # Provide this secret in Woodpecker with the full contents of your production .env
      - |
        if [ -n "$$APP_ENV_CONTENTS" ]; then
          printf "%s" "$$APP_ENV_CONTENTS" > .env
        fi

      # (C) Upload Laravel app (mirror with exclusions to keep it lean)
      - |
        lftp -e "
          set ssl:verify-certificate no;
          open -u $${FTP_CREDS};
          mirror --reverse --verbose \
                 --exclude-glob .git* \
                 --exclude-glob node_modules/ \
                 --exclude-glob front/ \
                 --exclude-glob tests/ \
                 --exclude-glob .woodpecker* \
                 --exclude-glob docker* \
                 --exclude-glob *.md \
                 --exclude-glob .*ignore \
                 ./ ${API_PATH};
          bye
        "

      # (E) Permissions (best-effort; Hostinger typically manages these)
      - echo "Deploy complete."
